In [12]:
import numpy as np

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
result = np.array([10, 15, 30, 45, 60])
print(result)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
result = np.arange(5,15)
print(result)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
result = np.arange(50, 100, 5)
print(result)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
result = np.zeros(10)
print(result)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
result = np.ones(10)
print(result)


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
result = np.linspace(0, 100, 5)
print(result)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
result = np.random.randint(10, 30, 5)
print(result)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
result = np.random.rand(10) # 0 < x < 1 => 0 < y < 2 => -1 < z < 1
result = result * 2 - 1
print(result)

result = np.random.uniform(-1,1,10)
print(result)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

result = np.random.uniform(10, 50, (3,5))
print(result)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplami = result.sum(axis=1) 
sutun_toplami = result.sum(axis=0)
print(satir_toplami)
print(sutun_toplami)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
# 18- Üretilen matrisin her bir elemanının karesini alınız.
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ?


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[19 22 12 15 22]
[ 0.89137068  0.57090228  0.58414419 -0.40515868 -0.60808331 -0.59109743
 -0.45805918  0.46210148  0.9891155   0.38884783]
[-0.84621811  0.62016262  0.2990261  -0.80778639  0.11610153  0.22096838
 -0.22460061 -0.77393857  0.42061856 -0.112467  ]
[[20.32215552 45.77585974 45.16745556 18.04712112 39.85910418]
 [35.15312927 41.63320728 12.47763721 12.78456683 11.39098671]
 [39.02410506 13.17961842 22.8465652  15.34406888 42.40647184]]
[169.17169612 113.4395273  132.8008294 ]
[ 94.49938986 100.58868543  80.49165797  46.17575683  93.65656273]


In [17]:
result = np.ones((6,6), dtype="int32")
print(result)
print("-"*20)

result[1:5, 1:5] = 0
print(result)
print("-"*20)

result[2:4, 2:4] = 2
print(result)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
--------------------
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
--------------------
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 2 2 0 1]
 [1 0 2 2 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]
